// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowChoThanh.MyDb;

#nullable disable

namespace ShowChoThanh.Migrations.ThaoDuocHoaHoiDb
{
    [DbContext(typeof(ThaoDuocHoaHoiDbContext))]
    [Migration("20240716091947_e4eq")]
    partial class e4eq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIHocTapTrucTuyen.Models.Domain.ChiTietThanhToan", b =>
                {
                    b.Property<string>("MaChiTietThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaChiTietThanhToan");

                    b.HasIndex("MaMay");

                    b.HasIndex("MaThanhToan");

                    b.ToTable("ChiTietThanhToans");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.AnhMayHoaHoi", b =>
                {
                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LinkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaMay");

                    b.ToTable("AnhMayHoaHois");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SoDu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.MayHoaHoi", b =>
                {
                    b.Property<string>("MaMay")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTaMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMay");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("MayHoaHois");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.ThanhToan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("APIHocTapTrucTuyen.Models.Domain.ChiTietThanhToan", b =>
                {
                    b.HasOne("ShowChoThanh.Models.Domain.MayHoaHoi", "mayHoaHoi")
                        .WithMany()
                        .HasForeignKey("MaMay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowChoThanh.Models.Domain.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("MaThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhToan");

                    b.Navigation("mayHoaHoi");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.AnhMayHoaHoi", b =>
                {
                    b.HasOne("ShowChoThanh.Models.Domain.MayHoaHoi", "MayHoaHoi")
                        .WithMany()
                        .HasForeignKey("MaMay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MayHoaHoi");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.MayHoaHoi", b =>
                {
                    b.HasOne("ShowChoThanh.Models.Domain.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ShowChoThanh.Models.Domain.ThanhToan", b =>
                {
                    b.HasOne("ShowChoThanh.Models.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
